//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemChung
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacSi
    {
        public string MaBS { get; set; }
        public string HoTenBS { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TrinhDo { get; set; }
        public string GioiTinh { get; set; }
    }
}
